spring:
  application:
    name: ars-core

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOSTNAME}:${DB_PORT}/${DB_ARS_DATABASE}
    username: ${DB_ARS_USER}
    password: ${DB_ARS_PASSWORD}

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/