spring:
  application:
    name: ars-core

  datasource:
    url: jdbc:postgresql://localhost:5432/ars_db
    username: ars_user
    password: ars_user_pass
    driver-class-name: org.postgresql.Driver

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/