spring:
  application:
    name: ars_audit

  data:
    mongodb:
      host: localhost
      port: 27017
      database: ars_db_mongo

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
